#!/bin/sh

set -e

echo using PICO_SDK_PATH=${PICO_SDK_PATH}

mkdir -p hardware

for item in ${PICO_SDK_PATH}/src/rp2_common/hardware_*; do
    cp -R ${item}/include/hardware/. hardware
    cp ${item}/*.c . ||:
done

cp -R ${PICO_SDK_PATH}/src/rp2350/hardware_regs/include/hardware/. hardware

cp -R ${PICO_SDK_PATH}/src/rp2350/hardware_structs/include/hardware/. hardware

cp -R ${PICO_SDK_PATH}/src/common/pico_base_headers/include/. .

cp -R ${PICO_SDK_PATH}/src/rp2350/pico_platform/include/. .

cp -R ${PICO_SDK_PATH}/src/rp2_common/pico_platform_compiler/include/. .
cp -R ${PICO_SDK_PATH}/src/rp2_common/pico_platform_sections/include/. .
cp -R ${PICO_SDK_PATH}/src/rp2_common/pico_platform_panic/include/. .

cat > pico/version.h <<EOF
/*
 * Copyright (c) 2020 Raspberry Pi (Trading) Ltd.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

// ---------------------------------------
// THIS FILE IS AUTOGENERATED; DO NOT EDIT
// ---------------------------------------

#ifndef _PICO_VERSION_H
#define _PICO_VERSION_H

#define PICO_SDK_VERSION_MAJOR    2
#define PICO_SDK_VERSION_MINOR    0
#define PICO_SDK_VERSION_REVISION 0
#define PICO_SDK_VERSION_STRING   "2.0.0"

#endif
EOF


cp -R ${PICO_SDK_PATH}/src/boards/include/boards/pico2.h .

cat > pico/config_autogen.h << EOF
#include "pico2.h"
EOF
